#!/bin/bash

echo "Enter file name: "
read Filename
touch $Filename

echo "Enter commit/message: "
read c

echo "Are you working on a branch? (yes/no): "
read answer

if [ "$answer" == "yes" ]; then
echo "Enter branch name: "
read bN

git add $Filename
git commit -m "$c"
git push origin $bN

else
git add $Filename
git commit -m "$c"
git push
fi
